(()=>{'use strict';
const KEY='cut31-v2';
const main=document.querySelector('#main'),nav=[...document.querySelectorAll('.nav-item')],toast=document.querySelector('#toast'),imp=document.querySelector('#importInput');
const TABATA_DEFAULTS={effort:15,rest:10,cycles:8};
const pad=n=>String(n).padStart(2,'0');
const isoNow=()=>{const d=new Date();return `${d.getFullYear()}-${pad(d.getMonth()+1)}-${pad(d.getDate())}`};
const esc=s=>String(s??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
const fmt=i=>{const[y,m,d]=i.split('-').map(Number);return new Intl.DateTimeFormat('fr-FR',{weekday:'long',day:'numeric',month:'long'}).format(new Date(y,m-1,d))};
const todayIndex=()=>{const i=DAYS.findIndex(d=>d.date===isoNow());return i<0?(isoNow()<CFG.start?0:DAYS.length-1):i};
const initialView=()=>{const v=new URLSearchParams(location.search).get('view');return ['today','program','tabata','progress','settings'].includes(v)?v:'today'};
const defaultState=()=>({view:initialView(),selected:todayIndex(),days:{},profile:{start:'',goal:''},tabata:{...TABATA_DEFAULTS}});
let state;
try{state={...defaultState(),...JSON.parse(localStorage.getItem(KEY)||'{}')};state.days=state.days||{};state.tabata={...TABATA_DEFAULTS,...(state.tabata||{})}}catch{state=defaultState()}
if(new URLSearchParams(location.search).has('view'))state.view=initialView();
function save(){localStorage.setItem(KEY,JSON.stringify(state))}
function entry(d,create=false){if(create&&!state.days[d.date])state.days[d.date]={weight:'',sleep:'',water:0,meals:{},ex:{},steps:false,promise:'',note:''};return state.days[d.date]||{weight:'',sleep:'',water:0,meals:{},ex:{},steps:false,promise:'',note:''}}
function donePct(d){const e=entry(d),total=d.menu.m.length+d.w.x.length+2,done=d.menu.m.filter((_,i)=>e.meals?.[i]).length+d.w.x.filter((_,i)=>e.ex?.[i]).length+(e.water>=3?1:0)+(e.steps?1:0);return total?Math.round(done/total*100):0}
function streak(){let idx=todayIndex();if(entry(DAYS[idx]).promise!=='yes')idx--;let n=0;for(;idx>=0&&entry(DAYS[idx]).promise==='yes';idx--)n++;return n}
function flash(t){toast.textContent=t;toast.classList.add('show');clearTimeout(flash.t);flash.t=setTimeout(()=>toast.classList.remove('show'),1700)}
function go(v){state.view=v;save();nav.forEach(b=>b.classList.toggle('active',b.dataset.view===v));render();scrollTo({top:0,behavior:'smooth'})}
function sectionHead(icon,title,meta=''){return `<div class="section-head"><div class="section-title"><div class="section-icon">${icon}</div><h2>${title}</h2></div>${meta?`<em>${meta}</em>`:''}</div>`}
function hero(d){const p=donePct(d);return `<section class="hero"><div class="hero-grid"><div><div class="eyebrow">Jour ${d.day} · ${d.date.slice(8,10)}/${d.date.slice(5,7)}</div><h1>${esc(fmt(d.date))}</h1><p>${esc(d.w.t)} · ${d.steps.toLocaleString('fr-FR')} pas</p><div class="streak-chip"><span>🔥</span><b>${streak()} jour${streak()>1?'s':''}</b><span>de streak</span></div></div><div class="activity-ring" style="--p:${p}"><div class="ring-inner"><b>${p}%</b><small>journée</small></div></div></div></section>`}
function waterControl(e){const water=Number(e.water||0),pct=Math.max(0,Math.min(100,water/3*100)),vals=[0,.5,1,1.5,2,2.5,3];return `<section class="section-card emphasis">${sectionHead('💧','Hydratation',`${water.toFixed(1).replace('.',',')} / 3,0 L`)}<div class="water-visual"><div class="water-drop"><svg viewBox="0 0 24 24" aria-hidden="true"><path d="M12 3.5S6.8 9.3 6.8 14a5.2 5.2 0 0 0 10.4 0C17.2 9.3 12 3.5 12 3.5Z"/></svg></div><div class="water-copy"><b>${water.toFixed(1).replace('.',',')} L</b><span>${water>=3?'Objectif hydratation atteint':'Tape sur un point pour mettre à jour'}</span></div></div><div class="water-rail"><div class="water-line" style="--water-p:${pct}%"><i></i></div>${vals.map(v=>`<button class="water-node ${water>=v?'on':''} ${water===v?'active':''}" data-water="${v}" aria-label="${String(v).replace('.',',')} litre"><span>${String(v).replace('.',',')}</span></button>`).join('')}</div></section>`}
function checkRow(kind,i,on,title,detail,tag=''){return `<label class="checkrow ${on?'checked':''}"><input type="checkbox" data-${kind}="${i}" ${on?'checked':''}><span class="box">✓</span><span><b>${esc(title)}</b><small>${detail}</small>${tag?`<span class="meal-tag">${tag}</span>`:''}</span><span class="row-chevron">›</span></label>`}
function today(){const d=DAYS[state.selected],e=entry(d);main.innerHTML=hero(d)+`<div class="quick-stats"><article class="quick-stat"><span>Calories</span><b>${CFG.cal}</b><small>kcal</small></article><article class="quick-stat"><span>Protéines</span><b>${CFG.protein}</b></article><article class="quick-stat"><span>Eau</span><b>3,0 L</b></article><article class="quick-stat"><span>Pas</span><b>${Math.round(d.steps/1000)}k</b></article></div>
<section class="section-card">${sectionHead('☀','Check-in','au réveil')}<div class="inputs"><div class="field"><label for="weight">Poids</label><input id="weight" inputmode="decimal" placeholder="ex. 89,4 kg" value="${esc(e.weight)}"></div><div class="field"><label for="sleep">Sommeil</label><input id="sleep" inputmode="decimal" placeholder="ex. 7,5 h" value="${esc(e.sleep)}"></div></div><p class="hint">Pas de petit-déjeuner imposé. Eau, café ou thé sans sucre si tu veux ; garde l’essentiel de tes calories pour des repas qui te rassasient.</p></section>
${waterControl(e)}
<section class="section-card">${sectionHead('🍽','Alimentation',esc(d.menu.p))}<div class="check-list">${d.menu.m.map((m,i)=>checkRow('meal',i,e.meals?.[i],m[0],m[1].map(esc).join(' · '),'Féculents pesés cuits')).join('')}</div><p class="hint">${esc(d.menu.k)} · huile, sauces, fromage et féculents à mesurer réellement.</p></section>
<section class="section-card">${sectionHead('⌁',esc(d.w.t),'1–3 reps en réserve')}<div class="check-list">${d.w.x.map((x,i)=>checkRow('ex',i,e.ex?.[i],x[0],esc(x[1]))).join('')}${`<label class="checkrow ${e.steps?'checked':''}"><input id="steps" type="checkbox" ${e.steps?'checked':''}><span class="box">✓</span><span><b>Objectif pas</b><small>${d.steps.toLocaleString('fr-FR')} pas aujourd’hui</small></span><span class="row-chevron">›</span></label>`}</div></section>
<section class="mind-card"><div class="section-kicker">Principe du jour</div><blockquote>${esc(d.quote)}</blockquote><div class="mind-row"><i>◎</i><div><b>Mission</b><br>${esc(d.mission)}</div></div><div class="mind-row"><i>✦</i><div><b>Visualisation</b><br>${esc(d.viz)}</div></div>${d.checkpoint?`<div class="checkpoint">${esc(d.checkpoint)}</div>`:''}</section>
<section class="section-card">${sectionHead('✓','Clôture','30 secondes')}<textarea id="note" placeholder="Victoire, difficulté, énergie, faim…">${esc(e.note)}</textarea><div class="promise"><button data-promise="yes" class="${e.promise==='yes'?'yes':''}">J’ai tenu ma parole</button><button data-promise="no" class="${e.promise==='no'?'no':''}">J’ai dévié</button></div></section>
<div class="daynav"><button id="prev" ${state.selected===0?'disabled':''}>← Jour précédent</button><button id="next" ${state.selected===30?'disabled':''}>Jour suivant →</button></div>`;
const E=entry(d,true),persist=()=>{E.weight=document.querySelector('#weight').value.replace(',','.');E.sleep=document.querySelector('#sleep').value.replace(',','.');E.note=document.querySelector('#note').value;save()};
document.querySelector('#weight').onchange=persist;document.querySelector('#sleep').onchange=persist;document.querySelector('#note').onchange=persist;
document.querySelectorAll('[data-water]').forEach(b=>b.onclick=()=>{E.water=+b.dataset.water;save();today()});
document.querySelectorAll('[data-meal]').forEach(c=>c.onchange=()=>{E.meals[c.dataset.meal]=c.checked;save();today()});
document.querySelectorAll('[data-ex]').forEach(c=>c.onchange=()=>{E.ex[c.dataset.ex]=c.checked;save();today()});
document.querySelector('#steps').onchange=c=>{E.steps=c.target.checked;save();today()};
document.querySelectorAll('[data-promise]').forEach(b=>b.onclick=()=>{E.promise=b.dataset.promise;save();today();flash(E.promise==='yes'?'Journée validée 🔥':'Écart enregistré — demain on repart')});
document.querySelector('#prev').onclick=()=>{state.selected--;save();today();scrollTo(0,0)};document.querySelector('#next').onclick=()=>{state.selected++;save();today();scrollTo(0,0)}
}
function program(){main.innerHTML=`<h1 class="pagetitle">Programme</h1><p class="subtitle">31 jours · 25 août → 24 septembre 2026</p><div class="calendar">${DAYS.map((d,i)=>{const p=donePct(d),e=entry(d);return `<button data-day="${i}" class="daycard ${i===state.selected?'sel':''}"><span>JOUR ${d.day}</span><b>${fmt(d.date).replace(/^./,c=>c.toUpperCase())}</b><small>${esc(d.w.t)} · ${p}% fait</small><i style="--p:${p}%"></i>${e.promise==='yes'?'<strong>✓</strong>':''}</button>`}).join('')}</div>`;document.querySelectorAll('[data-day]').forEach(b=>b.onclick=()=>{state.selected=+b.dataset.day;go('today')})}
function weights(){return DAYS.map(d=>({d,w:parseFloat(entry(d).weight)})).filter(x=>Number.isFinite(x.w))}
function chart(P){if(P.length<2)return '<div class="empty">Entre au moins deux pesées pour afficher la courbe.</div>';const W=600,H=210,min=Math.min(...P.map(p=>p.w))-.4,max=Math.max(...P.map(p=>p.w))+.4,xy=P.map((p,i)=>[30+i*(540/(P.length-1)),20+(max-p.w)*(160/(max-min))]);return `<svg viewBox="0 0 ${W} ${H}" class="chart"><path d="M${xy.map(a=>a.join(',')).join(' L')}"/><line x1="30" y1="180" x2="570" y2="180"/>${xy.map((a,i)=>`<circle cx="${a[0]}" cy="${a[1]}" r="5"><title>${P[i].d.date}: ${P[i].w} kg</title></circle>`).join('')}</svg>`}
function progress(){const P=weights(),first=P[0]?.w,last=P.at(-1)?.w,delta=Number.isFinite(first)&&Number.isFinite(last)?last-first:null,avg=Math.round(DAYS.reduce((a,d)=>a+donePct(d),0)/31),validated=DAYS.filter(d=>entry(d).promise==='yes').length;main.innerHTML=`<h1 class="pagetitle">Progression</h1><p class="subtitle">La tendance compte plus que le poids d’un seul matin.</p><div class="kpis"><article><b>${last?.toFixed(1)??'—'}</b><span>kg actuel</span></article><article><b>${delta==null?'—':`${delta>0?'+':''}${delta.toFixed(1)}`}</b><span>kg depuis départ</span></article><article><b>${validated}/31</b><span>jours validés</span></article></div><section class="section-card">${sectionHead('↗','Courbe de poids',`${P.length} pesée${P.length>1?'s':''}`)}${chart(P)}</section><section class="section-card">${sectionHead('◎','Exécution',`${avg}%`)}<div class="activity-ring" style="--p:${avg};margin:8px auto 4px"><div class="ring-inner"><b>${avg}%</b><small>global</small></div></div><p class="hint strong">Compare les moyennes de 7 jours. Tant que le poids baisse régulièrement et que ta force reste correcte, ne change pas le plan sur un chiffre isolé.</p></section>`}
let audioCtx=null;
let timer={mode:'idle',phase:'work',cycle:1,remaining:state.tabata.effort,duration:state.tabata.effort,endAt:0,interval:null,wake:null};
function beep(freq=880,duration=.09,count=1){try{audioCtx=audioCtx||new(window.AudioContext||window.webkitAudioContext)();if(audioCtx.state==='suspended')audioCtx.resume();for(let i=0;i<count;i++){const o=audioCtx.createOscillator(),g=audioCtx.createGain(),t=audioCtx.currentTime+i*.13;o.frequency.value=freq;o.type='sine';g.gain.setValueAtTime(.001,t);g.gain.exponentialRampToValueAtTime(.18,t+.01);g.gain.exponentialRampToValueAtTime(.001,t+duration);o.connect(g);g.connect(audioCtx.destination);o.start(t);o.stop(t+duration+.02)}}catch{}}
async function lockWake(){if(timer.wake||timer.mode!=='running'||!('wakeLock'in navigator))return;try{timer.wake=await navigator.wakeLock.request('screen');timer.wake.addEventListener?.('release',()=>timer.wake=null)}catch{}}
async function unlockWake(){try{await timer.wake?.release()}catch{}timer.wake=null}
function resetTimer(renderIt=true){clearInterval(timer.interval);timer.interval=null;unlockWake();timer={...timer,mode:'idle',phase:'work',cycle:1,remaining:state.tabata.effort,duration:state.tabata.effort,endAt:0,wake:null};if(renderIt&&state.view==='tabata')tabata()}
function advanceTimer(){if(timer.phase==='work'){timer.phase='rest';timer.remaining=state.tabata.rest;timer.duration=state.tabata.rest;timer.endAt=Date.now()+state.tabata.rest*1000;beep(520,.11,1)}else if(timer.cycle>=state.tabata.cycles){clearInterval(timer.interval);timer.interval=null;timer.mode='done';timer.remaining=0;timer.duration=1;unlockWake();beep(1040,.12,3);updateTimerDisplay();return}else{timer.cycle++;timer.phase='work';timer.remaining=state.tabata.effort;timer.duration=state.tabata.effort;timer.endAt=Date.now()+state.tabata.effort*1000;beep(940,.09,2)}updateTimerDisplay()}
function tick(){if(timer.mode!=='running')return;const raw=(timer.endAt-Date.now())/1000;if(raw<=0){advanceTimer();return}timer.remaining=raw;updateTimerDisplay()}
function startPauseTimer(){if(timer.mode==='done')resetTimer(false);if(timer.mode==='running'){timer.remaining=Math.max(.05,(timer.endAt-Date.now())/1000);timer.mode='paused';clearInterval(timer.interval);timer.interval=null;unlockWake();updateTimerDisplay();return}beep(740,.05,1);timer.mode='running';timer.endAt=Date.now()+timer.remaining*1000;timer.interval=setInterval(tick,100);lockWake();updateTimerDisplay()}
function updateTimerDisplay(){const card=document.querySelector('#timerCard'),time=document.querySelector('#timerTime'),phase=document.querySelector('#timerPhase'),cycle=document.querySelector('#timerCycle'),ring=document.querySelector('#timerRing'),start=document.querySelector('#timerStart');if(!card)return;const done=timer.mode==='done',pct=done?100:Math.max(0,Math.min(100,(timer.remaining/(timer.duration||1))*100));card.classList.toggle('resting',timer.phase==='rest'&&!done);card.classList.toggle('done',done);ring.style.setProperty('--tp',pct.toFixed(2));time.textContent=done?'✓':Math.max(0,Math.ceil(timer.remaining));phase.textContent=done?'Terminé':timer.phase==='work'?'Effort':'Récupération';cycle.textContent=done?`${state.tabata.cycles} cycles terminés`:`Cycle ${timer.cycle} / ${state.tabata.cycles}`;start.textContent=timer.mode==='running'?'Pause':timer.mode==='paused'?'Reprendre':timer.mode==='done'?'Recommencer':'Démarrer'}
function changeTabata(key,delta){if(timer.mode==='running'||timer.mode==='paused'){flash('Arrête le timer pour modifier les réglages');return}const min=key==='cycles'?1:5,max=key==='cycles'?50:120,step=key==='cycles'?1:5;state.tabata[key]=Math.max(min,Math.min(max,state.tabata[key]+delta*step));save();resetTimer(false);tabata()}
function applyPreset(effort,rest){if(timer.mode==='running'||timer.mode==='paused'){flash('Arrête le timer pour changer de preset');return}state.tabata.effort=effort;state.tabata.rest=rest;save();resetTimer(false);tabata()}
function stepper(key,label,value,suffix){return `<div class="stepper"><span>${label}</span><strong>${value}${suffix}</strong><div class="stepper-controls"><button data-step="${key}" data-dir="-1" aria-label="Diminuer ${label}">−</button><button data-step="${key}" data-dir="1" aria-label="Augmenter ${label}">+</button></div></div>`}
function tabata(){const t=state.tabata;main.innerHTML=`<div class="tabata-shell"><div class="tabata-hero"><div class="tabata-label">Interval training</div><h1 class="pagetitle">Tabata</h1><p class="subtitle">Configure, lance, puis laisse le timer conduire la séance.</p></div><div class="tabata-settings">${stepper('effort','Effort',t.effort,'s')}${stepper('rest','Récup',t.rest,'s')}${stepper('cycles','Cycles',t.cycles,'')}</div><div class="preset-row"><button class="preset ${t.effort===15&&t.rest===10?'active':''}" data-preset="15,10">15 / 10</button><button class="preset ${t.effort===20&&t.rest===10?'active':''}" data-preset="20,10">20 / 10</button><button class="preset ${t.effort===30&&t.rest===15?'active':''}" data-preset="30,15">30 / 15</button><button class="preset ${t.effort===40&&t.rest===20?'active':''}" data-preset="40,20">40 / 20</button></div><section id="timerCard" class="timer-card"><div id="timerRing" class="timer-ring"><div class="timer-center"><div id="timerPhase" class="timer-phase">Effort</div><div id="timerTime" class="timer-time">${t.effort}</div><div id="timerCycle" class="timer-cycle">Cycle 1 / ${t.cycles}</div></div></div><div class="timer-controls"><button id="timerStart" class="primary">Démarrer</button><button id="timerReset">Réinitialiser</button></div><div class="timer-note">Bips aux changements de phase · l’app tente de garder l’écran éveillé pendant la séance.</div></section></div>`;
document.querySelectorAll('[data-step]').forEach(b=>b.onclick=()=>changeTabata(b.dataset.step,+b.dataset.dir));document.querySelectorAll('[data-preset]').forEach(b=>b.onclick=()=>{const[a,r]=b.dataset.preset.split(',').map(Number);applyPreset(a,r)});document.querySelector('#timerStart').onclick=startPauseTimer;document.querySelector('#timerReset').onclick=()=>resetTimer();updateTimerDisplay()}
function settings(){main.innerHTML=`<h1 class="pagetitle">Réglages</h1><p class="subtitle">CUT 31 fonctionne localement sur ton appareil.</p><section class="section-card">${sectionHead('⌂','Installation iPhone')}<ol><li>Ouvre l’URL dans Safari.</li><li>Partager → Ajouter à l’écran d’accueil.</li><li>Active « Ouvrir comme app ».</li></ol></section><section class="section-card">${sectionHead('↧','Sauvegarde')}<div class="actions"><button id="export" class="action-button">Exporter mes données</button><button id="import" class="action-button">Importer une sauvegarde</button></div></section><section class="section-card">${sectionHead('🔔','Rappels')}<p class="hint strong">Les notifications iOS sont possibles pour une web-app installée, mais un rappel quotidien automatique nécessite un service Push côté serveur. Pour l’instant, l’automatisation Raccourcis iPhone reste la solution la plus simple.</p></section><section class="section-card">${sectionHead('!','Sécurité')}<p class="hint strong">Vertiges, malaise, douleur anormale, épuisement marqué ou symptôme préoccupant : arrête l’effort concerné et demande un avis médical.</p></section><button id="reset" class="danger">Réinitialiser toutes les données</button>`;document.querySelector('#export').onclick=exportData;document.querySelector('#import').onclick=()=>imp.click();document.querySelector('#reset').onclick=()=>{if(confirm('Effacer toutes les données ?')){localStorage.removeItem(KEY);state=defaultState();resetTimer(false);save();render();flash('Données réinitialisées')}}}
function exportData(){const blob=new Blob([JSON.stringify({...state,exportedAt:new Date().toISOString()},null,2)],{type:'application/json'}),u=URL.createObjectURL(blob),a=document.createElement('a');a.href=u;a.download=`cut31-${isoNow()}.json`;a.click();setTimeout(()=>URL.revokeObjectURL(u),500)}
imp.onchange=async()=>{try{const x=JSON.parse(await imp.files[0].text());if(!x.days)throw 0;state={...defaultState(),...x,days:x.days,tabata:{...TABATA_DEFAULTS,...(x.tabata||{})}};save();resetTimer(false);render();flash('Sauvegarde importée')}catch{flash('Fichier invalide')}imp.value=''};
function render(){nav.forEach(b=>b.classList.toggle('active',b.dataset.view===state.view));state.view==='program'?program():state.view==='tabata'?tabata():state.view==='progress'?progress():state.view==='settings'?settings():today()}
nav.forEach(b=>b.onclick=()=>go(b.dataset.view));document.querySelector('#jumpTodayBtn').onclick=()=>{state.selected=todayIndex();go('today')};
['gesturestart','gesturechange','gestureend'].forEach(type=>document.addEventListener(type,e=>e.preventDefault(),{passive:false}));document.addEventListener('touchmove',e=>{if(e.touches&&e.touches.length>1)e.preventDefault()},{passive:false});
try{if(screen.orientation?.lock)screen.orientation.lock('portrait-primary').catch(()=>{})}catch{}
document.addEventListener('visibilitychange',()=>{if(document.visibilityState==='visible'&&timer.mode==='running')lockWake()});
if('serviceWorker'in navigator)addEventListener('load',()=>navigator.serviceWorker.register('./sw.js').catch(()=>{}));save();render();
})();
