(()=>{'use strict';
const KEY='cut31-v2',main=document.querySelector('#main'),nav=[...document.querySelectorAll('.nav-item')],toast=document.querySelector('#toast'),imp=document.querySelector('#importInput');
const pad=n=>String(n).padStart(2,'0'),isoNow=()=>{const d=new Date();return `${d.getFullYear()}-${pad(d.getMonth()+1)}-${pad(d.getDate())}`},esc=s=>String(s??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
const fmt=i=>{const [y,m,d]=i.split('-').map(Number);return new Intl.DateTimeFormat('fr-FR',{weekday:'long',day:'numeric',month:'long'}).format(new Date(y,m-1,d))};
const defaultState=()=>({view:'today',selected:Math.max(0,Math.min(DAYS.length-1,DAYS.findIndex(d=>d.date===isoNow())<0?(isoNow()<CFG.start?0:DAYS.length-1):DAYS.findIndex(d=>d.date===isoNow()))),days:{},profile:{start:'',goal:''}});
let state;try{state={...defaultState(),...JSON.parse(localStorage.getItem(KEY)||'{}')};state.days=state.days||{}}catch{state=defaultState()}
function save(){localStorage.setItem(KEY,JSON.stringify(state))}function entry(d,create=false){if(create&&!state.days[d.date])state.days[d.date]={weight:'',sleep:'',water:0,meals:{},ex:{},steps:false,promise:'',note:''};return state.days[d.date]||{weight:'',sleep:'',water:0,meals:{},ex:{},steps:false,promise:'',note:''}}
function donePct(d){const e=entry(d),total=d.menu.m.length+d.w.x.length+2,done=d.menu.m.filter((_,i)=>e.meals?.[i]).length+d.w.x.filter((_,i)=>e.ex?.[i]).length+(e.water>=3?1:0)+(e.steps?1:0);return Math.round(done/total*100)}
function streak(){let idx=DAYS.findIndex(d=>d.date===isoNow());if(idx<0)idx=isoNow()<CFG.start?0:DAYS.length-1;if(entry(DAYS[idx]).promise!=='yes')idx--;let n=0;for(;idx>=0&&entry(DAYS[idx]).promise==='yes';idx--)n++;return n}
function flash(t){toast.textContent=t;toast.classList.add('show');clearTimeout(flash.t);flash.t=setTimeout(()=>toast.classList.remove('show'),1600)}
function go(v){state.view=v;save();nav.forEach(b=>b.classList.toggle('active',b.dataset.view===v));render();scrollTo({top:0,behavior:'smooth'})}
function hero(d){const p=donePct(d);return `<section class="hero"><div class="hero-top"><div><div class="eyebrow">JOUR ${d.day}/31</div><h1>${esc(fmt(d.date))}</h1><p>${esc(d.w.t)} · ${d.steps.toLocaleString('fr-FR')} pas</p></div><div class="streak"><b>${streak()} 🔥</b><small>streak</small></div></div><div class="progress-copy"><span>Journée</span><b>${p}%</b></div><div class="bar"><i style="width:${p}%"></i></div></section>`}
function today(){const d=DAYS[state.selected],e=entry(d);main.innerHTML=hero(d)+`<div class="stats"><article><span>Calories</span><b>${CFG.cal}</b><small>kcal</small></article><article><span>Protéines</span><b>${CFG.protein}</b></article><article><span>Eau</span><b>3 L</b></article><article><span>Pas</span><b>${Math.round(d.steps/1000)}k</b></article></div>
<section><header><h2>Check-in du matin</h2><em>avant de manger / boire</em></header><div class="inputs"><input id="weight" inputmode="decimal" placeholder="Poids (kg)" value="${esc(e.weight)}"><input id="sleep" inputmode="decimal" placeholder="Sommeil (h)" value="${esc(e.sleep)}"></div><p class="hint">Pas de petit-déjeuner imposé : eau, café ou thé sans sucre si tu veux. Le jeûne du matin est un outil de confort, pas une obligation.</p></section>
<section><header><h2>Hydratation</h2><em>${Number(e.water||0).toFixed(1)} / 3,0 L</em></header><div class="water">${[.5,1,1.5,2,2.5,3].map(v=>`<button data-water="${v}" class="${e.water>=v?'on':''}">${String(v).replace('.',',')} L</button>`).join('')}</div></section>
<section><header><h2>Alimentation</h2><em>${esc(d.menu.p)}</em></header>${d.menu.m.map((m,i)=>`<label class="checkrow ${e.meals?.[i]?'checked':''}"><input type="checkbox" data-meal="${i}" ${e.meals?.[i]?'checked':''}><span class="box">✓</span><span><b>${esc(m[0])}</b><small>${m[1].map(esc).join(' · ')}</small></span></label>`).join('')}<p class="hint">${esc(d.menu.k)} · féculents indiqués cuits · huile et sauces à peser.</p></section>
<section><header><h2>${esc(d.w.t)}</h2><em>1–3 reps en réserve</em></header>${d.w.x.map((x,i)=>`<label class="checkrow ${e.ex?.[i]?'checked':''}"><input type="checkbox" data-ex="${i}" ${e.ex?.[i]?'checked':''}><span class="box">✓</span><span><b>${esc(x[0])}</b><small>${esc(x[1])}</small></span></label>`).join('')}<label class="checkrow ${e.steps?'checked':''}"><input id="steps" type="checkbox" ${e.steps?'checked':''}><span class="box">✓</span><span><b>Objectif pas</b><small>${d.steps.toLocaleString('fr-FR')} pas aujourd’hui</small></span></label></section>
<section class="mind"><span>PRINCIPE DU JOUR</span><blockquote>${esc(d.quote)}</blockquote><p><b>Mission :</b> ${esc(d.mission)}</p><p><b>Visualisation :</b> ${esc(d.viz)}</p>${d.checkpoint?`<div class="checkpoint">${esc(d.checkpoint)}</div>`:''}</section>
<section><header><h2>Clôture</h2><em>30 secondes</em></header><textarea id="note" placeholder="Victoire / difficulté du jour…">${esc(e.note)}</textarea><div class="promise"><button data-promise="yes" class="${e.promise==='yes'?'yes':''}">J’ai tenu ma parole</button><button data-promise="no" class="${e.promise==='no'?'no':''}">J’ai dévié</button></div></section><div class="daynav"><button id="prev" ${state.selected===0?'disabled':''}>← Jour précédent</button><button id="next" ${state.selected===30?'disabled':''}>Jour suivant →</button></div>`;
const E=entry(d,true),persist=()=>{E.weight=document.querySelector('#weight').value.replace(',','.');E.sleep=document.querySelector('#sleep').value.replace(',','.');E.note=document.querySelector('#note').value;save()};document.querySelector('#weight').onchange=persist;document.querySelector('#sleep').onchange=persist;document.querySelector('#note').onchange=persist;document.querySelectorAll('[data-water]').forEach(b=>b.onclick=()=>{E.water=+b.dataset.water;save();today()});document.querySelectorAll('[data-meal]').forEach(c=>c.onchange=()=>{E.meals[c.dataset.meal]=c.checked;save();today()});document.querySelectorAll('[data-ex]').forEach(c=>c.onchange=()=>{E.ex[c.dataset.ex]=c.checked;save();today()});document.querySelector('#steps').onchange=c=>{E.steps=c.target.checked;save();today()};document.querySelectorAll('[data-promise]').forEach(b=>b.onclick=()=>{E.promise=b.dataset.promise;save();today();flash(E.promise==='yes'?'Journée validée 🔥':'Écart enregistré — demain on repart')});document.querySelector('#prev').onclick=()=>{state.selected--;save();today();scrollTo(0,0)};document.querySelector('#next').onclick=()=>{state.selected++;save();today();scrollTo(0,0)}}
function program(){main.innerHTML=`<h1 class="pagetitle">Programme 31 jours</h1><p class="subtitle">25 août → 24 septembre 2026</p><div class="calendar">${DAYS.map((d,i)=>{const p=donePct(d),e=entry(d);return `<button data-day="${i}" class="daycard ${i===state.selected?'sel':''}"><span>J${d.day}</span><b>${fmt(d.date).replace(/^./,c=>c.toUpperCase())}</b><small>${esc(d.w.t)}</small><i style="--p:${p}%"></i>${e.promise==='yes'?'<strong>✓</strong>':''}</button>`}).join('')}</div>`;document.querySelectorAll('[data-day]').forEach(b=>b.onclick=()=>{state.selected=+b.dataset.day;go('today')})}
function weights(){return DAYS.map(d=>({d,w:parseFloat(entry(d).weight)})).filter(x=>Number.isFinite(x.w))}function chart(P){if(P.length<2)return '<div class="empty">Entre au moins deux pesées pour afficher la courbe.</div>';const W=600,H=210,min=Math.min(...P.map(p=>p.w))-.4,max=Math.max(...P.map(p=>p.w))+.4,xy=P.map((p,i)=>[30+i*(540/(P.length-1)),20+(max-p.w)*(160/(max-min))]);return `<svg viewBox="0 0 ${W} ${H}" class="chart"><path d="M${xy.map(a=>a.join(',')).join(' L')}"/><line x1="30" y1="180" x2="570" y2="180"/>${xy.map((a,i)=>`<circle cx="${a[0]}" cy="${a[1]}" r="5"><title>${P[i].d.date}: ${P[i].w} kg</title></circle>`).join('')}</svg>`}
function progress(){const P=weights(),first=P[0]?.w,last=P.at(-1)?.w,delta=Number.isFinite(first)&&Number.isFinite(last)?last-first:null,avg=Math.round(DAYS.reduce((a,d)=>a+donePct(d),0)/31);main.innerHTML=`<h1 class="pagetitle">Progression</h1><p class="subtitle">Regarde la tendance, pas le bruit quotidien.</p><div class="kpis"><article><b>${last?.toFixed(1)??'—'}</b><span>kg actuel</span></article><article><b>${delta==null?'—':`${delta>0?'+':''}${delta.toFixed(1)}`}</b><span>kg depuis départ</span></article><article><b>${avg}%</b><span>exécution</span></article></div><section><header><h2>Courbe de poids</h2><em>${P.length} pesée${P.length>1?'s':''}</em></header>${chart(P)}</section><section><header><h2>Règle d’ajustement</h2></header><p class="hint strong">Compare les moyennes de 7 jours. Si la tendance baisse régulièrement et que la force reste correcte, ne change rien. N’abaisse pas brutalement les calories pour accélérer un chiffre isolé.</p></section>`}
function settings(){main.innerHTML=`<h1 class="pagetitle">Réglages</h1><p class="subtitle">Tes données restent sur cet appareil.</p><section><header><h2>Installation iPhone</h2></header><ol><li>Ouvre cette page dans Safari.</li><li>Partager → Ajouter à l’écran d’accueil.</li><li>Active “Ouvrir comme app” si proposé.</li></ol></section><section><header><h2>Sauvegarde</h2></header><div class="actions"><button id="export">Exporter mes données</button><button id="import">Importer une sauvegarde</button></div></section><section><header><h2>Sécurité</h2></header><p class="hint strong">Vertiges, malaise, douleur anormale, épuisement marqué ou symptôme préoccupant : arrête l’effort concerné et demande un avis médical. Ce carnet organise le programme ; il ne remplace pas un suivi médical.</p></section><button id="reset" class="danger">Réinitialiser toutes les données</button>`;document.querySelector('#export').onclick=exportData;document.querySelector('#import').onclick=()=>imp.click();document.querySelector('#reset').onclick=()=>{if(confirm('Effacer toutes les données ?')){localStorage.removeItem(KEY);state=defaultState();save();render();flash('Données réinitialisées')}}}
function exportData(){const blob=new Blob([JSON.stringify({...state,exportedAt:new Date().toISOString()},null,2)],{type:'application/json'}),u=URL.createObjectURL(blob),a=document.createElement('a');a.href=u;a.download=`cut31-${isoNow()}.json`;a.click();setTimeout(()=>URL.revokeObjectURL(u),500)}
imp.onchange=async()=>{try{const x=JSON.parse(await imp.files[0].text());if(!x.days)throw 0;state={...defaultState(),...x,days:x.days};save();render();flash('Sauvegarde importée')}catch{flash('Fichier invalide')}imp.value=''};
function render(){nav.forEach(b=>b.classList.toggle('active',b.dataset.view===state.view));state.view==='program'?program():state.view==='progress'?progress():state.view==='settings'?settings():today()}
nav.forEach(b=>b.onclick=()=>go(b.dataset.view));document.querySelector('#jumpTodayBtn').onclick=()=>{const i=DAYS.findIndex(d=>d.date===isoNow());state.selected=i<0?(isoNow()<CFG.start?0:30):i;go('today')};
if('serviceWorker'in navigator)addEventListener('load',()=>navigator.serviceWorker.register('./sw.js').catch(()=>{}));save();render();
})();
