const CFG={start:'2026-08-25',end:'2026-09-24',cal:'1900–2000',protein:'160–180 g',water:3,sleep:7.5};
const MENUS={
A:{k:'≈ 1 900–2 000 kcal',p:'≈ 165–175 g protéines',m:[['Midi',['Poulet 200 g','Riz cuit 250 g','Légumes 300 g','Huile d’olive 10 g','Sauce skyr + moutarde']],['Collation',['Skyr ou fromage blanc 0 % 300 g','1 banane']],['Soir',['Poisson blanc 250 g','Pommes de terre cuites 400 g','Légumes 300 g','2 œufs','1 fruit']]]},
B:{k:'≈ 1 900–2 000 kcal',p:'≈ 165–175 g protéines',m:[['Midi',['Dinde 200 g','Pâtes cuites 250 g','Légumes 300 g','Sauce tomate','Parmesan 15 g max']],['Collation',['Skyr 300 g','1 pomme ou 1 banane']],['Soir',['Steak haché 5 % 200 g','Pommes de terre cuites 350 g','Grande salade','Fromage blanc 0 % 250 g']]]},
C:{k:'≈ 1 900–2 000 kcal',p:'≈ 160–175 g protéines',m:[['Midi',['Poulet 200 g','Semoule cuite 250 g','Légumes 300 g','Huile d’olive 10 g']],['Collation',['Fromage blanc 0 % 300 g','1 pomme']],['Soir',['3 œufs','Blancs d’œufs 250 g','Pommes de terre cuites 300 g','Grande salade','Pain complet 2 tranches']]]},
D:{k:'≈ 1 900–2 000 kcal',p:'≈ 165–180 g protéines',m:[['Midi',['Steak haché 5 % 200 g','Riz cuit 250 g','Salade + tomates + concombre','Sauce au skyr']],['Collation',['Fromage blanc 0 % 300 g','1 fruit']],['Soir',['Poulet 220 g','Pommes de terre cuites 350 g','Légumes 300 g','Skyr 200 g']]]},
F:{k:'≈ 1 900–2 000 kcal',p:'≈ 165–175 g protéines',m:[['Midi — plaisir contrôlé',['Burger maison : pain + steak 5 % 150–180 g','1 tranche fromage','Salade + tomate + oignon','Pommes de terre au four 300 g','Sauce légère mesurée']],['Collation',['Skyr 300 g','1 fruit']],['Soir',['Poulet ou poisson 220–250 g','Légumes 300 g','Riz cuit 180 g ou pommes de terre 300 g','Fromage blanc 0 % 200 g']]]},
G:{k:'≈ 1 850–1 950 kcal',p:'≈ 165–180 g protéines',m:[['Midi',['Poisson blanc 250 g','Pommes de terre cuites 400 g','Légumes 300 g','Huile d’olive 10 g']],['Collation',['Skyr 300 g','1 pomme']],['Soir',['Poulet 220 g','Riz cuit 220 g','Légumes 300 g','2 œufs']]]}
};
const W={
UA:{t:'Upper A + cardio',x:[['Développé couché','4 × 6–8'],['Tirage vertical','4 × 8–10'],['Développé incliné haltères','3 × 8–10'],['Rowing','3 × 8–12'],['Élévations latérales','3 × 15–20'],['Curl biceps','2 × 10–15'],['Triceps poulie','2 × 10–15'],['Marche inclinée','20 min']]},
LA:{t:'Lower A + cardio',x:[['Hack squat ou squat','4 × 6–10'],['Soulevé de terre roumain','3 × 8–10'],['Presse','3 × 10–12'],['Leg curl','3 × 10–15'],['Mollets','3 × 12–20'],['Crunch câble','3 × 12–15'],['Cardio tranquille','15–20 min']]},
UB:{t:'Upper B + cardio',x:[['Développé épaules','3 × 6–10'],['Chest press','3 × 8–12'],['Rowing poulie','3 × 8–12'],['Tirage vertical','3 × 10–12'],['Élévations latérales','3 × 15–20'],['Curl biceps','2 × 10–15'],['Triceps','2 × 10–15'],['Marche inclinée','20 min']]},
LB:{t:'Lower B',x:[['Presse ou hack squat','4 × 8–12'],['Fentes bulgares','3 × 8–12 / jambe'],['Hip thrust','3 × 8–12'],['Leg curl','3 × 10–15'],['Leg extension','2 × 10–15'],['Mollets','3 × 15–20'],['Abdos','3 séries']]},
Z:{t:'Zone 2',x:[['Cardio Zone 2','50 min — marche inclinée, vélo ou elliptique']]},
ZL:{t:'Zone 2 + marche',x:[['Marche active / Zone 2','60 min — rythme régulier']]},
R:{t:'Récupération active',x:[['Marche','12 000 pas'],['Mobilité légère','10 min optionnel']]},
LM:{t:'Lower A — volume réduit',x:[['Hack squat ou squat','2–3 × 6–10'],['Soulevé de terre roumain','2–3 × 8–10'],['Presse','2 × 10–12'],['Leg curl','2 × 10–15'],['Mollets','2 × 12–20'],['Abdos','2 séries optionnel']]},
ZF:{t:'Zone 2 léger',x:[['Marche Zone 2','40–45 min'],['Mobilité','10 min']]}
};
const Q=[
'Tu n’as pas besoin d’être parfait. Arrête de négocier avec ce que tu as décidé.','La motivation ouvre la porte ; la discipline te fait rester.','Ce qui est difficile aujourd’hui devient banal avec la répétition.','Mesure ta journée à ce que tu fais, pas à ton envie de le faire.','Les samedis ordinaires construisent plus que les lundis motivés.','La maîtrise vaut plus que la privation.','Tu contrôles tes actions, pas le chiffre exact de la balance.','Progresser légèrement bat l’enthousiasme irrégulier.','Ne gagne pas le mois aujourd’hui. Gagne cette journée.','Une habitude demande moins de volonté qu’une décision répétée.','Ton corps répond aux répétitions, pas aux promesses.','Chaque décision tenue renforce ta confiance en toi.','Profiter sans perdre le contrôle est une forme de discipline.','Les chiffres sont des informations, pas des jugements.','L’inconfort n’est pas automatiquement un signal d’arrêt.','Contrôler ton rythme aide à contrôler tes décisions.','Ton attention finit souvent par diriger ton comportement.','La différence vient de centaines de décisions simples.','Cherche une série de journées correctes, pas une journée parfaite.','Plaisir et objectif peuvent coexister quand tu décides des limites.','Le miroir quotidien masque parfois le changement que les photos révèlent.','Bien finir est une compétence différente de bien commencer.','Ce qui est mesuré devient plus difficile à rationaliser.','Parfois la meilleure action pour demain est de dormir.','Tu n’as plus à prouver que tu peux commencer : prouve que tu peux finir.','L’objectif n’est pas de souffrir plus, mais d’exécuter mieux.','La récompense est le résultat, pas le sabotage du résultat.','La patience est une action quand le processus est correct.','Reste fidèle au processus quand le résultat devient visible.','Un chiffre honnête vaut mieux qu’un chiffre manipulé.','Tu n’avais qu’une journée à réussir à la fois.'
];
const M=[
'Aucune calorie imprévue aujourd’hui.','Termine la séance avec 1–3 reps en réserve.','Fais ton cardio sans transformer la récupération en punition.','Prépare le dîner avant d’avoir très faim.','Pèse l’huile et les sauces.','Repas plaisir contrôlé : pas de cheat day.','Calcule ta première moyenne de poids.','Cherche une répétition de plus sur quelques mouvements.','Ne change rien au plan sur une seule pesée.','Mange lentement : 15–20 min par repas.','Garde le téléphone loin pendant le dîner.','Conserve ta force plutôt que chasser l’épuisement.','Profite sans dette alimentaire à “rembourser”.','Compare moyenne S1 et S2, pas deux matins.','Reste propre techniquement même si tu es en déficit.','Bois réellement 3 L aujourd’hui.','Aucune nourriture devant écran ce soir.','Couche-toi assez tôt pour 7 h 30+ de sommeil.','Prends tes légumes aux deux repas principaux.','Garde ton dimanche sous contrôle.','Photos face, profil, dos dans la même lumière.','Finis aussi sérieusement que tu as commencé.','Mesure tes 3 L, pas d’estimation vague.','30 min sans téléphone avant de dormir.','Ne relâche pas parce que la fin approche.','Dernière grosse séance jambes : propre, pas suicidaire.','Aucune récompense alimentaire hors plan.','Repas simples et prévisibles.','Pas de record inutile cette semaine.','Volume réduit : arrive frais au bilan.','Hydratation normale, aucune déshydratation pour la balance.'
];
const V=[
'Imagine le 25 septembre : plus léger et surtout fier d’avoir tenu ta parole.','Visualise la sortie de salle après une séance exécutée sans négocier.','Vois ce rythme devenir normal plutôt qu’exceptionnel.','Imagine ton dîner déjà décidé avant que la faim arrive.','Vois ton futur toi reconnaissant de ce samedi bien géré.','Imagine profiter d’un repas tout en gardant la maîtrise.','Visualise une courbe qui descend malgré quelques rebonds.','Vois tes performances rester solides pendant que le poids baisse.','Imagine une journée simple, sans bataille mentale inutile.','Vois ton cardio devenir plus facile.','Imagine tes repas préparés et la décision déjà prise.','Vois-toi dire non à une impulsion sans frustration.','Imagine fermer la journée plaisir sans culpabilité.','Regarde mentalement les données comme un tableau de bord.','Vois la fatigue temporaire comme un passage.','Imagine manger plus lentement et sentir la satiété.','Vois une soirée calme où tu contrôles ton attention.','Imagine les petites décisions qui fabriquent la différence visuelle.','Vois-toi accumuler les jours corrects.','Imagine un dimanche agréable et maîtrisé.','Visualise les photos côte à côte.','Imagine la satisfaction de finir aussi fort que tu as commencé.','Vois tes bouteilles d’eau comme un compteur simple.','Imagine ton réveil après une vraie nuit de sommeil.','Vois la ligne d’arrivée et refuse de ralentir.','Imagine sortir de la dernière grosse séance avec le travail fait.','Vois-toi fermer le dimanche sans dette alimentaire.','Imagine les derniers jours comme une formalité déjà préparée.','Vois un chiffre honnête obtenu sans artifice.','Imagine ralentir juste assez pour arriver frais au bilan.','Visualise le bilan complet : poids, taille, photos, force et 31 jours exécutés.'
];
const S=[['UA',10000,'A'],['LA',12000,'A'],['Z',13000,'D'],['UB',12000,'B'],['LB',12000,'C'],['ZL',14000,'F'],['R',12000,'G'],['UA',12000,'A'],['LA',12000,'B'],['Z',13000,'C'],['UB',12000,'A'],['LB',12000,'D'],['ZL',14000,'F'],['R',12000,'G'],['UA',12000,'A'],['LA',12000,'B'],['Z',13000,'C'],['UB',12000,'A'],['LB',12000,'D'],['ZL',14000,'F'],['R',12000,'G'],['UA',12000,'A'],['LA',12000,'D'],['Z',14000,'B'],['UB',12000,'A'],['LB',12000,'D'],['ZL',14000,'F'],['R',12000,'G'],['UA',12000,'A'],['LM',12000,'B'],['ZF',12000,'A']];
const checkpoints={7:'Bilan S1 : calcule la moyenne des pesées, sans réagir à un rebond.',14:'Bilan S2 : compare les moyennes. Si la perte est régulière, ne change rien.',21:'Checkpoint visuel : photos face, profil et dos dans les mêmes conditions.',28:'Dernière ligne droite : ne cherche pas à accélérer brutalement.',31:'Demain : pesée au réveil, tour de taille, photos et bilan de force.'};
function addDay(iso,n){const [y,m,d]=iso.split('-').map(Number),x=new Date(Date.UTC(y,m-1,d+n));return x.toISOString().slice(0,10)}
const DAYS=S.map((r,i)=>({day:i+1,date:addDay(CFG.start,i),w:W[r[0]],steps:r[1],menu:MENUS[r[2]],quote:Q[i],mission:M[i],viz:V[i],checkpoint:checkpoints[i+1]||''}));
DAYS[0].menu={k:'≈ 1 900–2 000 kcal',p:'Priorité : finir haut en protéines',m:[['Midi — déjà pris',['3 sandwichs pain complet + thon','Energy drink sans sucre','Évite une sauce calorique non mesurée']],['Collation',['Skyr ou fromage blanc 0 % 300 g','1 fruit']],['Soir',['Poulet 220 g','Pommes de terre cuites 350 g','Légumes 300 g','Huile d’olive 10 g max','Skyr 200 g si besoin']]]};
